const giftCardDatas = [
	[
		'feature-1.jpg',
		'feature-2.jpg',
		'feature-3.jpg',
		'feature-4.jpg',
		'feature-5.png',
		'feature-6.jpg',
		'feature-7.jpg',
		'feature-8.png',
		'feature-9.jpg',
		'feature-10.png',
		'feature-11.png',
		'feature-12.jpg',
		'feature-13.png',
		'feature-14.png',
		'feature-15.png',
		'feature-16.jpg',
		'feature-17.png',
		'feature-18.png',
		'feature-19.png',
		'feature-20.jpg',
	],
	[
		'image copy 5.png',
		'image copy 6.png',
		'image copy 7.png',
		'image copy 8.png',
	],
	[
		'image copy 17.png',
		'image copy 18.png',
		'image copy 19.png',
		'image copy 20.png',
		'image copy 31.png',
		'image copy 32.png',
		'image copy 33.png',
	],
	[
		'image copy 21.png',
		'image copy 22.png',
		'image copy 23.png',
	],
	[
		'image copy 17.png',
		'image copy 18.png',
		'image copy 19.png',
		'image copy 20.png',
		'image copy 31.png',
		'image copy 32.png',
		'image copy 33.png',
	],
	[
		'image copy 21.png',
		'image copy 22.png',
		'image copy 23.png',
	],
	[
		'image copy 24.png',
		'image copy 25.png',
		'image copy 26.png',
	],
	[
		'image copy 27.png',
		'image copy 28.png',
		'image copy 29.png',
		'image copy 30.png',
	],
	[
		'image copy 6.png',
		'image copy 7.png',
		'image copy 8.png',
	],
];

export { giftCardDatas };
