const giftCardDatas = [
	[
		'../../images/gift-card/feature-1.jpg',
		'../../images/gift-card/feature-2.jpg',
		'../../images/gift-card/feature-3.jpg',
		'../../images/gift-card/feature-4.jpg',
		'../../images/gift-card/feature-5.png',
		'../../images/gift-card/feature-6.jpg',
		'../../images/gift-card/feature-7.jpg',
		'../../images/gift-card/feature-8.png',
		'../../images/gift-card/feature-9.jpg',
		'../../images/gift-card/feature-10.png',
		'../../images/gift-card/feature-11.png',
		'../../images/gift-card/feature-12.jpg',
		'../../images/gift-card/feature-13.png',
		'../../images/gift-card/feature-14.png',
		'../../images/gift-card/feature-15.png',
		'../../images/gift-card/feature-16.jpg',
		'../../images/gift-card/feature-17.png',
		'../../images/gift-card/feature-18.png',
		'../../images/gift-card/feature-19.png',
		'../../images/gift-card/feature-20.jpg',
	],
	[
		'../../images/gift-card/image copy 5.png',
		'../../images/gift-card/image copy 6.png',
		'../../images/gift-card/image copy 7.png',
		'../../images/gift-card/image copy 8.png',
	],
	[
		'../../images/gift-card/image copy 17.png',
		'../../images/gift-card/image copy 18.png',
		'../../images/gift-card/image copy 19.png',
		'../../images/gift-card/image copy 20.png',
		'../../images/gift-card/image copy 31.png',
		'../../images/gift-card/image copy 32.png',
		'../../images/gift-card/image copy 33.png',
	],
	[
		'../../images/gift-card/image copy 21.png',
		'../../images/gift-card/image copy 22.png',
		'../../images/gift-card/image copy 23.png',
	],
	[
		'../../images/gift-card/image copy 17.png',
		'../../images/gift-card/image copy 18.png',
		'../../images/gift-card/image copy 19.png',
		'../../images/gift-card/image copy 20.png',
		'../../images/gift-card/image copy 31.png',
		'../../images/gift-card/image copy 32.png',
		'../../images/gift-card/image copy 33.png',
	],
	[
		'../../images/gift-card/image copy 21.png',
		'../../images/gift-card/image copy 22.png',
		'../../images/gift-card/image copy 23.png',
	],
	[
		'../../images/gift-card/image copy 24.png',
		'../../images/gift-card/image copy 25.png',
		'../../images/gift-card/image copy 26.png',
	],
	[
		'../../images/gift-card/image copy 27.png',
		'../../images/gift-card/image copy 28.png',
		'../../images/gift-card/image copy 29.png',
		'../../images/gift-card/image copy 30.png',
	],
	[
		'../../images/gift-card/image copy 6.png',
		'../../images/gift-card/image copy 7.png',
		'../../images/gift-card/image copy 8.png',
	],
];

export { giftCardDatas };
