export const itemArr = [
    {
        item_id: 0,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p18.jpg",
        item_name: "Caffe Americano",
        item_type: "Americanos",
    },
    {
        item_id: 1,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 2,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 3,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 4,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 5,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 6,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 7,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 8,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 9,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 10,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 11,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p3.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 12,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p19.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 13,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p20.jpg",
        item_name: "Coffee Americano",
        item_type: "Brewed Coffees",
    },
    {
        item_id: 14,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p15.jpg",
        item_name: "Coffee Americano",
        item_type: "Cappuccinos",
    },
    {
        item_id: 15,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p15.jpg",
        item_name: "Coffee Americano",
        item_type: "Espresso Shots",
    },
    {
        item_id: 15,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p11.jpg",
        item_name: "Coffee Americano",
        item_type: "Espresso Con Panna",
    },
    {
        item_id: 16,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p11.jpg",
        item_name: "Coffee Americano",
        item_type: "Espresso Con Panna",
    },
    {
        item_id: 17,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p3.jpg",
        item_name: "Coffee Americano",
        item_type: "Flat Whites",
    },
    {
        item_id: 18,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p3.jpg",
        item_name: "Coffee Americano",
        item_type: "Flat Whites",
    },
    {
        item_id: 19,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p23.jpg",
        item_name: "Coffee Americano",
        item_type: "Lattes",
    },
    {
        item_id: 20,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p22.jpg",
        item_name: "Coffee Americano",
        item_type: "Lattes",
    },
    {
        item_id: 21,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p23.jpg",
        item_name: "Coffee Americano",
        item_type: "Lattes",
    },
    {
        item_id: 22,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p22.jpg",
        item_name: "Coffee Americano",
        item_type: "Lattes",
    },
    {
        item_id: 23,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p23.jpg",
        item_name: "Coffee Americano",
        item_type: "Lattes",
    },
    {
        item_id: 24,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p5.jpg",
        item_name: "Coffee Americano",
        item_type: "Macchiatos",
    },
    {
        item_id: 25,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p10.jpg",
        item_name: "Coffee Americano",
        item_type: "Lattes",
    },
    {
        item_id: 26,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p21.jpg",
        item_name: "Coffee Americano",
        item_type: "Mochas",
    },
    {
        item_id: 26,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p21.jpg",
        item_name: "Coffee Americano",
        item_type: "Mochas",
    },
    {
        item_id: 27,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p21.jpg",
        item_name: "Coffee Americano",
        item_type: "Mochas",
    },
    {
        item_id: 28,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p6.jpg",
        item_name: "Coffee Americano",
        item_type: "Coffee Travelers",
    },
    {
        item_id: 29,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p6.jpg",
        item_name: "Coffee Americano",
        item_type: "Coffee Travelers",
    },
    {
        item_id: 30,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p6.jpg",
        item_name: "Coffee Americano",
        item_type: "Coffee Travelers",
    },
    {
        item_id: 31,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p6.jpg",
        item_name: "Coffee Americano",
        item_type: "Coffee Travelers",
    },
    {
        item_id: 32,
        sub_category_id: 0,
        item_img_path: "./hot-drink-img/p6.jpg",
        item_name: "Coffee Americano",
        item_type: "Coffee Travelers",
    },

    // Cold Drink
    {
        item_id: 33,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p3.jpg",
        item_name: "White Chocolate Macadamia Cream Cold Brew",
        item_type: "Cold Brews",
    },
    {
        item_id: 34,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p3.jpg",
        item_name: "White Chocolate Macadamia Cream Cold Brew",
        item_type: "Cold Brews",
    },
    {
        item_id: 35,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p3.jpg",
        item_name: "White Chocolate Macadamia Cream Cold Brew",
        item_type: "Cold Brews",
    },
    {
        item_id: 36,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p6.jpg",
        item_name: "White Chocolate Macadamia Cream Cold Brew",
        item_type: "Cold Brews",
    },
    {
        item_id: 37,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p4.jpg",
        item_name: "White Chocolate Macadamia Cream Cold Brew",
        item_type: "Cold Brews",
    },
    {
        item_id: 38,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p5.jpg",
        item_name: "White Chocolate Macadamia Cream Cold Brew",
        item_type: "Cold Brews",
    },
    {
        item_id: 38,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p5.jpg",
        item_name: "Cinnamon Caramel Cream Nitro Cold Brews",
        item_type: "Nitro Cold Brews",
    },
    {
        item_id: 39,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p17.jpg",
        item_name: "Cinnamon Caramel Cream Nitro Cold Brews",
        item_type: "Nitro Cold Brews",
    },
    {
        item_id: 40,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p3.jpg",
        item_name: "Cinnamon Caramel Cream Iced Mochas",
        item_type: "Iced Mochas",
    },
    {
        item_id: 41,
        sub_category_id: 1,
        item_img_path: "./cold-drink-img/p3.jpg",
        item_name: "Cinnamon Caramel Cream Iced Mochas",
        item_type: "Iced Mochas",
    },

    // Starbucks Refreshers® Beverages
    {
        item_id: 42,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p1.jpg",
        item_name: "Spicy Pineapple",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 43,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p3.jpg",
        item_name: "Strawberry Acai Lemondae Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 44,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p5.jpg",
        item_name: "Mango Dragonfruit Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 45,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p6.jpg",
        item_name:
            "Pineapple Passionfruit Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 46,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p2.jpg",
        item_name: "Spicy Dragonfruit",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 47,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p7.jpg",
        item_name:
            "Frozen Strawberry Acai Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 48,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p8.jpg",
        item_name:
            "Frozen Mango Dragonfruit Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 49,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p9.jpg",
        item_name:
            "Frozen Pineapple Passionfruit Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 50,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p17.jpg",
        item_name:
            "Frozen Pineapple Passionfruit Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },
    {
        item_id: 51,
        sub_category_id: 2,
        item_img_path: "./starbucks-refreshers-img/p15.jpg",
        item_name:
            "Frozen Pineapple Passionfruit Lemonade Starbucks Refreshers Beverage",
        item_type: "Lemonades and Frozen",
    },

    // Frappuccino® Blended Beverages
    {
        item_id: 52,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p2.jpg",
        item_name: "Mocha Cookie Crumble Frappuccino",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 53,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p14.jpg",
        item_name: "Caramel Ribbon Crunch Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 54,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p7.jpg",
        item_name: "Espresso Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 55,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p5.jpg",
        item_name: "Caffe Vanilla Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 56,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p6.jpg",
        item_name: "Caramel Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 57,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p4.jpg",
        item_name: "Coffee Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 58,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p8.jpg",
        item_name: "Mocha Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 59,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p17.jpg",
        item_name: "Java Chip Frappuccino Blended Beverages",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 52,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p10.jpg",
        item_name: "White Chocolate Mocha Frappuccino",
        item_type: "Coffee Frappuccino®",
    },
    {
        item_id: 53,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p11.jpg",
        item_name: "Lavender Creme Frappuccino Blended Beverage",
        item_type: "Creme Frappuccino®",
    },
    {
        item_id: 54,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p12.jpg",
        item_name: "Lavender Creme Frappuccino Blended Beverage",
        item_type: "Creme Frappuccino®",
    },
    {
        item_id: 55,
        sub_category_id: 3,
        item_img_path: "./frappuccino-img/p14.jpg",
        item_name: "Lavender Creme Frappuccino Blended Beverage",
        item_type: "Creme Frappuccino®",
    },
    // Food -> Hot Breakfast
  {
    item_id: 100,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p1.jpg",
    item_name: "Chicken Maple Egg Sandwich",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 101,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p2.jpg",
    item_name: "Ham & Swiss Croissant",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 102,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p3.jpg",
    item_name: "Sausage Cheddar Muffin",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 103,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p4.jpg",
    item_name: "Bacon Gouda Sandwich",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 104,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p5.jpg",
    item_name: "Spinach Feta Wrap",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 105,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p6.jpg",
    item_name: "Avocado Spread Toast",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 106,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p7.jpg",
    item_name: "Egg White Bites",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 107,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p8.jpg",
    item_name: "Turkey Bacon Egg",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 108,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p9.jpg",
    item_name: "Double Smoked Bacon",
    item_type: "Breakfast Sandwiches & Wraps",
  },
  {
    item_id: 109,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p10.jpg",
    item_name: "Red Pepper Egg Bites",
    item_type: "Bakes & Egg Bites",
  },
  {
    item_id: 110,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p11.jpg",
    item_name: "Cheese Egg Bites",
    item_type: "Bakes & Egg Bites",
  },
  {
    item_id: 111,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p12.jpg",
    item_name: "Mushroom Egg Bites",
    item_type: "Bakes & Egg Bites",
  },
  {
    item_id: 112,
    sub_category_id: 4,
    item_img_path: "hot-breakfast-img/p13.jpg",
    item_name: "Spinach Egg Bites",
    item_type: "Bakes & Egg Bites",
  },

  // Food -> Oatmeal & Yogurt
  {
    item_id: 113,
    sub_category_id: 5,
    item_img_path: "oatmeal-img/p1.jpg",
    item_name: "Classic Oatmeal",
    item_type: "Oatmeal & Yogurt",
  },
  {
    item_id: 114,
    sub_category_id: 5,
    item_img_path: "oatmeal-img/p2.jpg",
    item_name: "Strawberry Parfait",
    item_type: "Oatmeal & Yogurt",
  },

  // Food -> Bakery
  {
    item_id: 115,
    sub_category_id: 6,
    item_img_path: "bakery-img/p1.jpg",
    item_name: "Chocolate Croissant",
    item_type: "Bakery",
  },
  {
    item_id: 116,
    sub_category_id: 6,
    item_img_path: "bakery-img/p2.jpg",
    item_name: "Blueberry Muffin",
    item_type: "Bakery",
  },
  {
    item_id: 117,
    sub_category_id: 6,
    item_img_path: "bakery-img/p3.jpg",
    item_name: "Almond Croissant",
    item_type: "Bakery",
  },

  // Cake Pops
  {
    item_id: 118,
    sub_category_id: 6,
    item_img_path: "bakery-img/p4.jpg",
    item_name: "Birthday Cake Pop",
    item_type: "Cake Pops",
  },
  {
    item_id: 120,
    sub_category_id: 6,
    item_img_path: "bakery-img/p5.jpg",
    item_name: "Chocolate Cake Pop",
    item_type: "Cake Pops",
  },
  {
    item_id: 121,
    sub_category_id: 6,
    item_img_path: "bakery-img/p6.jpg",
    item_name: "Cookies Cream Pop",
    item_type: "Cake Pops",
  },

  // Cookies, Brownies & Bars
  {
    item_id: 122,
    sub_category_id: 6,
    item_img_path: "bakery-img/p7.jpg",
    item_name: "Chocolate Chip Cookie",
    item_type: "Cookies, Brownies & Bars",
  },
  {
    item_id: 123,
    sub_category_id: 6,
    item_img_path: "bakery-img/p8.jpg",
    item_name: "Double Chocolate Brownie",
    item_type: "Cookies, Brownies & Bars",
  },
  {
    item_id: 124,
    sub_category_id: 6,
    item_img_path: "bakery-img/p9.jpg",
    item_name: "Cranberry Bliss Bar",
    item_type: "Cookies, Brownies & Bars",
  },

  // Croissants
  {
    item_id: 125,
    sub_category_id: 6,
    item_img_path: "bakery-img/p10.jpg",
    item_name: "Butter Croissant",
    item_type: "Croissants",
  },
  {
    item_id: 126,
    sub_category_id: 6,
    item_img_path: "bakery-img/p11.jpg",
    item_name: "Almond Croissant",
    item_type: "Croissants",
  },
  {
    item_id: 127,
    sub_category_id: 6,
    item_img_path: "bakery-img/p12.jpg",
    item_name: "Chocolate Croissant",
    item_type: "Croissants",
  },

  // Loaves, Cakes & Buns
  {
    item_id: 128,
    sub_category_id: 6,
    item_img_path: "bakery-img/p13.jpg",
    item_name: "Lemon Pound Cake",
    item_type: "Loaves, Cakes & Buns",
  },
  {
    item_id: 129,
    sub_category_id: 6,
    item_img_path: "bakery-img/p14.jpg",
    item_name: "Banana Nut Bread",
    item_type: "Loaves, Cakes & Buns",
  },
  {
    item_id: 130,
    sub_category_id: 6,
    item_img_path: "bakery-img/p15.jpg",
    item_name: "Pumpkin Bread",
    item_type: "Loaves, Cakes & Buns",
  },
  {
    item_id: 131,
    sub_category_id: 6,
    item_img_path: "bakery-img/p16.jpg",
    item_name: "Iced Lemon Loaf",
    item_type: "Loaves, Cakes & Buns",
  },
  {
    item_id: 132,
    sub_category_id: 6,
    item_img_path: "bakery-img/p17.jpg",
    item_name: "Cinnamon Swirl Cake",
    item_type: "Loaves, Cakes & Buns",
  },

  // Danishes & Doughnuts
  {
    item_id: 133,
    sub_category_id: 6,
    item_img_path: "bakery-img/p18.jpg",
    item_name: "Cheese Danish",
    item_type: "Danishes & Doughnuts",
  },
  {
    item_id: 134,
    sub_category_id: 6,
    item_img_path: "bakery-img/p19.jpg",
    item_name: "Cherry Danish",
    item_type: "Danishes & Doughnuts",
  },
  {
    item_id: 135,
    sub_category_id: 6,
    item_img_path: "bakery-img/p20.jpg",
    item_name: "Old-Fashioned Doughnut",
    item_type: "Danishes & Doughnuts",
  },

  // Muffins & Scones
  {
    item_id: 136,
    sub_category_id: 6,
    item_img_path: "bakery-img/p21.jpg",
    item_name: "Blueberry Muffin",
    item_type: "Muffins & Scones",
  },
  {
    item_id: 137,
    sub_category_id: 6,
    item_img_path: "bakery-img/p22.jpg",
    item_name: "Pumpkin Scone",
    item_type: "Muffins & Scones",
  },

  // Food -> Lunch
  // Warm Sandwiches
  {
    item_id: 138,
    sub_category_id: 7,
    item_img_path: "lunch-img/p1.jpg",
    item_name: "Turkey Pesto Panini",
    item_type: "Warm Sandwiches",
  },
  {
    item_id: 139,
    sub_category_id: 7,
    item_img_path: "lunch-img/p2.jpg",
    item_name: "Ham & Cheese Panini",
    item_type: "Warm Sandwiches",
  },
  {
    item_id: 140,
    sub_category_id: 7,
    item_img_path: "lunch-img/p3.jpg",
    item_name: "Roast Beef Panini",
    item_type: "Warm Sandwiches",
  },

  // Protein Boxes
  {
    item_id: 141,
    sub_category_id: 7,
    item_img_path: "lunch-img/p4.jpg",
    item_name: "Chicken & Quinoa Protein Box",
    item_type: "Protein Boxes",
  },
  {
    item_id: 142,
    sub_category_id: 7,
    item_img_path: "lunch-img/p5.jpg",
    item_name: "Egg & Cheese Protein Box",
    item_type: "Protein Boxes",
  },

  // Snacks & Sweets
  // Packaged Snacks
  {
    item_id: 143,
    sub_category_id: 8,
    item_img_path: "snacks-img/p1.jpg",
    item_name: "Kettle Potato Chips",
    item_type: "Packaged Snacks",
  },
  {
    item_id: 144,
    sub_category_id: 8,
    item_img_path: "snacks-img/p2.jpg",
    item_name: "Organic Popcorn",
    item_type: "Packaged Snacks",
  },
  {
    item_id: 145,
    sub_category_id: 8,
    item_img_path: "snacks-img/p3.jpg",
    item_name: "Granola Bar",
    item_type: "Packaged Snacks",
  },

  // Fruit & Nut
  {
    item_id: 146,
    sub_category_id: 8,
    item_img_path: "snacks-img/p4.jpg",
    item_name: "Fruit & Nut Blend",
    item_type: "Fruit & Nut",
  },
  {
    item_id: 147,
    sub_category_id: 8,
    item_img_path: "snacks-img/p5.jpg",
    item_name: "Dried Mango",
    item_type: "Fruit & Nut",
  },

  // Sweets
  {
    item_id: 148,
    sub_category_id: 8,
    item_img_path: "snacks-img/p6.jpg",
    item_name: "Almond Chocolate Delight",
    item_type: "Sweets",
  },
  {
    item_id: 149,
    sub_category_id: 8,
    item_img_path: "snacks-img/p7.jpg",
    item_name: "Dark Chocolate Espresso Bark",
    item_type: "Sweets",
  },
  {
    item_id: 150,
    sub_category_id: 8,
    item_img_path: "snacks-img/p8.jpg",
    item_name: "Caramel Sea Salt Treat",
    item_type: "Sweets",
  },

  {
    item_id: 151,
    sub_category_id: 8,
    item_img_path: "snacks-img/p3.jpg",
    item_name: "Classic Chocolate Chip Cookies",
    item_type: "Biscotti & Cookies",
  },
  {
    item_id: 152,
    sub_category_id: 8,
    item_img_path: "snacks-img/p4.jpg",
    item_name: "Double Chocolate Biscotti",
    item_type: "Biscotti & Cookies",
  },
  {
    item_id: 153,
    sub_category_id: 8,
    item_img_path: "snacks-img/p5.jpg",
    item_name: "Candy Crunch Chocolate",
    item_type: "Chocolates & Candy",
  },
  {
    item_id: 154,
    sub_category_id: 8,
    item_img_path: "snacks-img/p6.jpg",
    item_name: "Mint Chocolate Candy",
    item_type: "Chocolates & Candy",
  },
  {
    item_id: 155,
    sub_category_id: 8,
    item_img_path: "snacks-img/p7.jpg",
    item_name: "Fruity Candy Mix",
    item_type: "Chocolates & Candy",
  },
  {
    item_id: 156,
    sub_category_id: 8,
    item_img_path: "snacks-img/p8.jpg",
    item_name: "Nutty Trail Mix",
    item_type: "Fruit & Nuts",
  },
  {
    item_id: 157,
    sub_category_id: 8,
    item_img_path: "snacks-img/p9.jpg",
    item_name: "Tropical Fruit Nut Medley",
    item_type: "Fruit & Nuts",
  },
  {
    item_id: 158,
    sub_category_id: 8,
    item_img_path: "snacks-img/p10.jpg",
    item_name: "Berry Nut Blend",
    item_type: "Fruit & Nuts",
  },
  {
    item_id: 159,
    sub_category_id: 8,
    item_img_path: "snacks-img/p11.jpg",
    item_name: "Mixed Nuts and Raisins",
    item_type: "Fruit & Nuts",
  },
  {
    item_id: 160,
    sub_category_id: 8,
    item_img_path: "snacks-img/p12.jpg",
    item_name: "Peppermint Gum",
    item_type: "Gum & Mints",
  },
  {
    item_id: 161,
    sub_category_id: 8,
    item_img_path: "snacks-img/p13.jpg",
    item_name: "Buttery Popcorn",
    item_type: "Popcorn & Chips",
  },
  {
    item_id: 162,
    sub_category_id: 8,
    item_img_path: "snacks-img/p14.jpg",
    item_name: "Cheddar Cheese Chips",
    item_type: "Popcorn & Chips",
  },
  {
    item_id: 163,
    sub_category_id: 8,
    item_img_path: "snacks-img/p15.jpg",
    item_name: "Salted Caramel Popcorn",
    item_type: "Popcorn & Chips",
  },
  {
    item_id: 164,
    sub_category_id: 8,
    item_img_path: "snacks-img/p16.jpg",
    item_name: "Spicy Jalapeno Chips",
    item_type: "Popcorn & Chips",
  },
  {
    item_id: 165,
    sub_category_id: 8,
    item_img_path: "snacks-img/p17.jpg",
    item_name: "Sliced Salami and Cheese",
    item_type: "Meat & Cheese",
  },
  {
    item_id: 166,
    sub_category_id: 8,
    item_img_path: "snacks-img/p18.jpg",
    item_name: "Prosciutto Wrapped Mozzarella",
    item_type: "Meat & Cheese",
  },
  {
    item_id: 167,
    sub_category_id: 8,
    item_img_path: "snacks-img/p19.jpg",
    item_name: "Almond Protein Bar",
    item_type: "Snack Bars",
  },
  {
    item_id: 168,
    sub_category_id: 8,
    item_img_path: "snacks-img/p20.jpg",
    item_name: "Peanut Butter Energy Bar",
    item_type: "Snack Bars",
  },
  {
    item_id: 169,
    sub_category_id: 8,
    item_img_path: "snacks-img/p21.jpg",
    item_name: "Granola Oats Bar",
    item_type: "Snack Bars",
  },
  {
    item_id: 170,
    sub_category_id: 8,
    item_img_path: "snacks-img/p22.jpg",
    item_name: "Dark Chocolate Nutrition Bar",
    item_type: "Snack Bars",
  },

  // At Home Coffee -> Whole bean
  {
    item_id: 171,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p1.jpg",
    item_name: "Reserve Roast Whole Bean",
    item_type: "Starbucks Reserve",
  },
  {
    item_id: 172,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p2.jpg",
    item_name: "Espresso Roast Whole Bean",
    item_type: "Blonde Roast",
  },
  {
    item_id: 173,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p3.jpg",
    item_name: "Blonde Roast Whole Bean",
    item_type: "Blonde Roast",
  },
  {
    item_id: 174,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p4.jpg",
    item_name: "Dark Roast Whole Bean",
    item_type: "Medium Roast",
  },
  {
    item_id: 175,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p5.jpg",
    item_name: "Italian Roast Whole Bean",
    item_type: "Medium Roast",
  },
  {
    item_id: 176,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p6.jpg",
    item_name: "French Roast Whole Bean",
    item_type: "Medium Roast",
  },
  {
    item_id: 177,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p7.jpg",
    item_name: "Columbian Roast Whole Bean",
    item_type: "Medium Roast",
  },
  {
    item_id: 178,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p8.jpg",
    item_name: "Sumatra Roast Whole Bean",
    item_type: "Medium Roast",
  },
  {
    item_id: 179,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p9.jpg",
    item_name: "Veranda Blend Whole Bean",
    item_type: "Medium Roast",
  },
  {
    item_id: 180,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p10.jpg",
    item_name: "Pike Place Roast Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 181,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p11.jpg",
    item_name: "Holiday Blend Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 182,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p12.jpg",
    item_name: "Caffe Verona Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 183,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p13.jpg",
    item_name: "Guatemala Antigua Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 184,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p14.jpg",
    item_name: "Kenya Roast Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 185,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p15.jpg",
    item_name: "Ethiopia Roast Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 186,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p16.jpg",
    item_name: "Decaf Pike Place Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 187,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p17.jpg",
    item_name: "Christmas Blend Whole Bean",
    item_type: "Dark Roast",
  },
  {
    item_id: 188,
    sub_category_id: 9,
    item_img_path: "whole-bean-img/p18.jpg",
    item_name: "Anniversary Blend Whole Bean",
    item_type: "Dark Roast",
  },

  // At Home Coffee -> VIA® Instant
  {
    item_id: 189,
    sub_category_id: 10,
    item_img_path: "via-instant-img/p1.jpg",
    item_name: "VIA® Instant Italian Roast",
    item_type: "Flavored",
  },
  {
    item_id: 190,
    sub_category_id: 10,
    item_img_path: "via-instant-img/p2.jpg",
    item_name: "VIA® Instant French Roast",
    item_type: "Blonde Roast",
  },
  {
    item_id: 191,
    sub_category_id: 10,
    item_img_path: "via-instant-img/p3.jpg",
    item_name: "VIA® Instant Pike Place",
    item_type: "Medium Roast",
  },
  {
    item_id: 192,
    sub_category_id: 10,
    item_img_path: "via-instant-img/p4.jpg",
    item_name: "VIA® Instant Veranda Blend",
    item_type: "Dark Roast",
  },
  {
    item_id: 193,
    sub_category_id: 10,
    item_img_path: "via-instant-img/p5.jpg",
    item_name: "VIA® Instant Decaf Italian Roast",
    item_type: "Dark Roast",
  },
  {
    item_id: 194,
    sub_category_id: 10,
    item_img_path: "via-instant-img/p5.jpg",
    item_name: "VIA® Instant Decaf Italian Roast",
    item_type: "Dark Roast",
  },

  // Cold Cups
  {
    item_id: 200,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p3.avif",
    item_name: "White Siren Bling Plastic Cold Cup - 16 fl oz",
    item_type: "",
  },
  {
    item_id: 201,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p4.avif",
    item_name: "White Siren Bling Plastic Cold Cup - 24 fl oz",
    item_type: "",
  },
  {
    item_id: 202,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p5.avif",
    item_name: "UV Color-Changing Plastic Reusable Cold Cup with Straw - 24 fl oz",
    item_type: "",
  },
  {
    item_id: 203,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p6.avif",
    item_name: "Sky Blue Soft-Touch Stainless-Steel Vacuum Cold Cup - 24 fl oz",
    item_type: "",
  },
  {
    item_id: 204,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p7.avif",
    item_name: "Multicolor Plastic Reusable Cold Cup with Dome Lid, 5-Pack - 24 fl oz",
    item_type: "",
  },
  {
    item_id: 205,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p1.jpg",
    item_name: "Plastic Reusable Cold Cup with Lid & Straw - 24 fl oz",
    item_type: "",
  },
  {
    item_id: 206,
    sub_category_id: 11,
    item_img_path: "cold-cup-img/p2.jpg",
    item_name: "Siren Logo Plastic Cold Cup - 24 fl oz",
    item_type: "",
  },

  // Tumblers
  {
    item_id: 207,
    sub_category_id: 12,
    item_img_path: "tumblers-img/tumblers.jpg",
    item_name: "Siren Logo Plastic Hot Cup - 16 fl oz",
    item_type: "",
  },

  // Mugs
  {
    item_id: 208,
    sub_category_id: 13,
    item_img_path: "mugs-img/mug.avif",
    item_name: "Glass Mug - 16 fl oz",
    item_type: "",
  },

  // Water Bottles
  {
    item_id: 209,
    sub_category_id: 14,
    item_img_path: "water-bottles-img/waterbottles.avif",
    item_name: "Twist to Sip Stainless-Steel Water Bottle - 20 fl oz",
    item_type: "",
  },

  // Other
  {
    item_id: 210,
    sub_category_id: 15,
    item_img_path: "other-img/p1.jpg",
    item_name: "French Press",
    item_type: "",
  },
  {
    item_id: 211,
    sub_category_id: 15,
    item_img_path: "other-img/p2.jpg",
    item_name: "Pour Over",
    item_type: "",
  },
  {
    item_id: 212,
    sub_category_id: 15,
    item_img_path: "other-img/p3.avif",
    item_name: "Small Shopping Bag",
    item_type: "",
  },
];